import type { UiLanguage, Translations } from "@/types";

export const translations: Record<UiLanguage, Translations> = {
  en: {
    appName: "LinguaLens",
    newSession: "New Session",
    uploadImage: "Upload Image",
    uploadInstruction: "Drag & drop an image here, or click to select",
    dragDropOr: "or",
    browseFiles: "Browse Files",
    selectOcrLanguages: "Select OCR Language(s)",
    suggestLanguages: "Suggest Languages (AI)",
    extractText: "Extract Text",
    extractedText: "Extracted Text",
    textCopied: "Text copied to clipboard!",
    copyToClipboard: "Copy to Clipboard",
    downloadTxt: "Download .txt",
    downloadDocx: "Download .docx",
    undo: "Undo",
    redo: "Redo",
    characterCount: "Characters",
    wordCount: "Words",
    noActiveSession: "No active session. Create a new one to start!",
    sessionPrefix: "Session",
    errorImageLoad: "Error loading image. Please try a different one.",
    errorOcr: "OCR process failed. The image might be unreadable or not contain text in the selected languages.",
    errorNoTextFound: "No text found in the image with the selected languages.",
    errorTextDownload: "Error preparing text for download.",
    loadingOcr: "Extracting text...",
    loadingSuggestions: "Analyzing image...",
    languages: {
      en: "English",
      am: "Amharic",
      om: "Oromifa",
      ti: "Tigrinya",
    },
    ocrLanguages: {
      eng: "English",
      amh: "Amharic",
      orm: "Oromo",
      tir: "Tigrinya",
    },
    aiSuggested: "AI Suggested",
  },
  am: {
    appName: "ሊንጓሌንስ",
    newSession: "አዲስ ክፍለ ጊዜ",
    uploadImage: "ምስል ስቀል",
    uploadInstruction: "ምስል እዚህ ይጎትቱ እና ይጣሉ፣ ወይም ለመምረጥ ጠቅ ያድርጉ",
    dragDropOr: "ወይም",
    browseFiles: "ፋይሎችን ያስሱ",
    selectOcrLanguages: "የOCR ቋንቋ(ዎች) ይምረጡ",
    suggestLanguages: "ቋንቋዎችን ጠቁም (AI)",
    extractText: "ጽሑፍ አውጣ",
    extractedText: "የወጣ ጽሑፍ",
    textCopied: "ጽሑፍ ወደ ቅንጥብ ሰሌዳ ተቀድቷል!",
    copyToClipboard: "ወደ ቅንጥብ ሰሌዳ ቅዳ",
    downloadTxt: ".txt አውርድ",
    downloadDocx: ".docx አውርድ",
    undo: "ቀልብስ",
    redo: "ድገም",
    characterCount: "ቁምፊዎች",
    wordCount: "ቃላት",
    noActiveSession: "ንቁ ክፍለ ጊዜ የለም። ለመጀመር አዲስ ይፍጠሩ!",
    sessionPrefix: "ክፍለ ጊዜ",
    errorImageLoad: "ምስል በመጫን ላይ ስህተት። እባክዎ የተለየ ይሞክሩ።",
    errorOcr: "የOCR ሂደት አልተሳካም። ምስሉ የማይነበብ ወይም በተመረጡት ቋንቋዎች ጽሑፍ የሌለው ሊሆን ይችላል።",
    errorNoTextFound: "በተመረጡት ቋንቋዎች በምስሉ ላይ ምንም ጽሑፍ አልተገኘም።",
    errorTextDownload: "ጽሑፍ ለማውረድ በማዘጋጀት ላይ ስህተት።",
    loadingOcr: "ጽሑፍ በማውጣት ላይ...",
    loadingSuggestions: "ምስል በመተንተን ላይ...",
    languages: {
      en: "እንግሊዝኛ",
      am: "አማርኛ",
      om: "ኦሮምኛ",
      ti: "ትግርኛ",
    },
    ocrLanguages: {
      eng: "እንግሊዝኛ",
      amh: "አማርኛ",
      orm: "ኦሮምኛ",
      tir: "ትግርኛ",
    },
    aiSuggested: "AI የተጠቆመ",
  },
  om: {
    appName: "LinguaLens", // Placeholder, needs Oromifa translation
    newSession: "Garee Haaraa",
    uploadImage: "Suura Olkaa'i",
    uploadInstruction: "Suura asitti harkisiitii buusi, yookiin filachuuf cuqaasi",
    dragDropOr: "yookiin",
    browseFiles: "Faayiloota Sakatta'i",
    selectOcrLanguages: "Afaan(oota) OCR Filadhu",
    suggestLanguages: "Afaanota Yaada Kenni (AI)",
    extractText: "Barruu Baasi",
    extractedText: "Barruu Baafame",
    textCopied: "Barruun gara kilippoordii koppii ta'eera!",
    copyToClipboard: "Gara Kilippoordii Koppii Godhi",
    downloadTxt: ".txt Buufadhu",
    downloadDocx: ".docx Buufadhu",
    undo: "Deebisi",
    redo: "Irra Deebi'i",
    characterCount: "Qubee",
    wordCount: "Jechoota",
    noActiveSession: "Gareen hojiirra jiru hin jiru. Jalqabuuf haaraa uumi!",
    sessionPrefix: "Garee",
    errorImageLoad: "Suura fe'uu irratti dogoggorri uumame. Maaloo kan biraa yaali.",
    errorOcr: "Adeemsi OCR milkaa'uu dide. Suurri dubbifamuu dhiisuu danda'a ykn afaanota filataman keessatti barruu hin qabu ta'a.",
    errorNoTextFound: "Afaanota filataman keessatti suuricha irratti barruun hin argamne.",
    errorTextDownload: "Barruu buufachuuf qopheessuu irratti dogoggorri uumame.",
    loadingOcr: "Barruu baasaa jira...",
    loadingSuggestions: "Suura qorachaa jira...",
    languages: {
      en: "Ingiliffa",
      am: "Amaariffa",
      om: "Afaan Oromoo",
      ti: "Tigriffa",
    },
    ocrLanguages: {
      eng: "Ingiliffa",
      amh: "Amaariffa",
      orm: "Oromoo",
      tir: "Tigriffa",
    },
    aiSuggested: "AI Yaadni Kenname",
  },
  ti: {
    appName: "ሊንጓሌንስ", // Placeholder, needs Tigrinya translation
    newSession: "ሓድሽ सत्र",
    uploadImage: "ስእሊ ስቀል",
    uploadInstruction: "ስእሊ ኣብዚ ጎተት ኣቢልካ ኣውርድ፣ ወይ ንምምራጽ ጠውቕ",
    dragDropOr: "ወይ",
    browseFiles: "ፋይላት ኣለሹ",
    selectOcrLanguages: "ቋንቋ(ታት) OCR ምረጽ",
    suggestLanguages: "ቋንቋታት ምኽሪ ሃብ (AI)",
    extractText: "ጽሑፍ ኣውጽእ",
    extractedText: "ዝወጸ ጽሑፍ",
    textCopied: "ጽሑፍ ናብ ቅንጥብ ሰሌዳ ተቐዲሑ!",
    copyToClipboard: "ናብ ቅንጥብ ሰሌዳ ቅዳሕ",
    downloadTxt: ".txt ኣውርድ",
    downloadDocx: ".docx ኣውርድ",
    undo: "መልስ",
    redo: "ደግም",
    characterCount: "ፊደላት",
    wordCount: "ቃላት",
    noActiveSession: "ንቑሕ सत्र የለን። ንምጅማር ሓድሽ ፍጠር!",
    sessionPrefix: "Sessዩን",
    errorImageLoad: "ስእሊ ኣብ ምጽዓን ስሕተት ኣጋጢሙ። በጃኻ ካልእ ፈትን።",
    errorOcr: "መስርሕ OCR ኣይተሳለጠን። ስእሊ ዘይንበብ ወይ ኣብ ምሩጻት ቋንቋታት ጽሑፍ ዘይብሉ ክኸውን ይኽእል እዩ።",
    errorNoTextFound: "ኣብ ምሩጻት ቋንቋታት ኣብ ስእሊ ዝኾነ ጽሑፍ ኣይተረኽበን።",
    errorTextDownload: "ጽሑፍ ንምውራድ ኣብ ምድላው ስሕተት ኣጋጢሙ።",
    loadingOcr: "ጽሑፍ እናውጸአ...",
    loadingSuggestions: "ስእሊ እናተንተነ...",
    languages: {
      en: "እንግሊዝኛ",
      am: "ኣምሓርኛ",
      om: "ኦሮምኛ",
      ti: "ትግርኛ",
    },
    ocrLanguages: {
      eng: "እንግሊዝኛ",
      amh: "ኣምሓርኛ",
      orm: "ኦሮምኛ",
      tir: "ትግርኛ",
    },
    aiSuggested: "AI ዝተማኸረ",
  },
};

export const availableUiLanguages: { value: UiLanguage; label: string }[] = [
  { value: "en", label: "English" },
  { value: "am", label: "አማርኛ" },
  { value: "om", label: "Afaan Oromoo" },
  { value: "ti", label: "ትግርኛ" },
];

export const availableOcrLanguages: { value: OcrLanguage; labelKey: keyof Translations['ocrLanguages'] }[] = [
  { value: "eng", labelKey: "eng" },
  { value: "amh", labelKey: "amh" },
  { value: "orm", labelKey: "orm" },
  { value: "tir", labelKey: "tir" },
];

export const aiLanguageToOcrLanguageMap: Record<AiLanguage, OcrLanguage> = {
  en: "eng",
  am: "amh",
  or: "orm",
  ti: "tir",
};

export const ocrLanguageToAiLanguageMap: Record<OcrLanguage, AiLanguage> = {
  eng: "en",
  amh: "am",
  orm: "or",
  tir: "ti",
};
